#!/bin/bash

function usage() {
    echo "usage: ./$(basename $0) path_to_param.h"
}

if [ $# -lt 1 ]; then
    echo "no input .h file!"
    usage
    exit 1
fi

H_NAME=$1
MSP_OUT_PATH=$2
BIN_NAME=${H_NAME/.h/.bin}

if [ -z "$MSP_OUT_PATH" ]; then
    output=$(strings _makebin)
    glibc=$(echo "$output" | grep -oP 'msp_out:\K.*')
    msp_out_path=$(echo "$glibc" | sed 's/ *%s *//g')

    MSP_OUT_PATH="$msp_out_path"
fi

IN_STUB_NAME=ax_isp_stub
OUT_STUB_NAME=ax_isp_params
awk -f gen_stub.awk $H_NAME > $IN_STUB_NAME.c
if [ $? -ne 0 ]; then
    echo failed to gen $IN_STUB_NAME.c
    exit 10;
fi

cat $IN_STUB_NAME.h $H_NAME $IN_STUB_NAME.c > $OUT_STUB_NAME.c
if [ $? -ne 0 ]; then
    echo failed to gen $OUT_STUB_NAME.c
    exit 20;
fi

gcc -g $OUT_STUB_NAME.c -fPIC -shared -o $OUT_STUB_NAME.so -I$MSP_OUT_PATH/include -I../include
if [ $? -ne 0 ]; then
    echo failed to gen $OUT_STUB_NAME.so
    exit 30;
fi

./_makebin > $BIN_NAME
if [ $? -ne 0 ]; then
    echo error occur when writing bin
    exit 100;
fi
